### ISSUE TITLE
Cambiar readme

### ISSUE THREAD

**Issue by tatianamolinari** [proyectoarq1/productoscuidados#37]
- Agregar heroku

**Comment by ChristianDaniel** [comment]
No entendí esta tarea :/
Te referís a poner lo de New Relic??

**Comment by tatianamolinari** [comment]
Pues clarooooooooooo :)

**Comment by ChristianDaniel** [comment]
Tenés que ser más descriptiva en las tarjetas :P

**Comment by tatianamolinari** [comment]
.   ¯\_(ツ)_/¯ .
